# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: graphael-rails 0.1.5 ruby lib

Gem::Specification.new do |s|
  s.name = "graphael-rails"
  s.version = "0.1.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["christian schwartz"]
  s.date = "2014-12-30"
  s.description = "raphael and graphael bundle for rails"
  s.email = "christian.schwartz@informatik.uni-wuerzburg.de"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".gitmodules",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "graphael-rails.gemspec",
    "lib/graphael-rails.rb"
  ]
  s.homepage = "http://github.com/cschwartz/graphael-rails"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "raphael and graphael bundle for rails"

  s.add_development_dependency("jeweler")
end

